### ISSUE TITLE
Homepage is mostly useless

### ISSUE THREAD

**Issue by cunidev** [zachomedia/apple-music-webplayer#61]
It would be better for the homepage to show something more than the current welcome message, as having to go to Recommendations for example each time is slightly counterintuitive. I'd suggest to show recently listened songs on the homepage, and keep the welcome message below.

**Comment by zachomedia** [comment]
This was an intentional design decision at the time because loading anything on the homepage slowed down the page and delayed you from getting where you wanted quickly.

I think since then there are have been improvements to how stuff is loaded (primarily the artwork), so we might be able to look at adding things to that page again.
