### ISSUE TITLE
Fetch Ratings Error: Unable to fetch your song ratings. 

### ISSUE THREAD

**Issue by FurkanToprak** [zachomedia/apple-music-webplayer#80]
`Fetch Ratings Error: Unable to fetch your song ratings. ` arises multiple times upon opening my Firefox browser on Ubuntu 18.04.2 LTS.

**Comment by zachomedia** [comment]
Thanks for the report.

Which page are you on when you get the errors?

**Comment by zachomedia** [comment]
Also, does it happen on all pages (with a songs list) or just some of them?

**Comment by FurkanToprak** [comment]
I believe the error is raised 3 times per played song and, as far as I can tell, only occurs under songs in my library.

**Comment by zachomedia** [comment]
Though I couldn't reproduce part of the issue (I couldn't get the error to appear), but I did see failed requests to fetch the ratings as part of the queue / history feature.

Looks like something in MusicKit JS has changed, which caused a lot of issues with the ratings feature in the queue list. I've now disabled loading ratings for the queue list and disabled the play history since much of it wasn't working correctly.

Please let me know if you stop seeing the issue. This will still need more work, but hopefully should remove the annoying popup.

**Comment by zachomedia** [comment]
I think I've fixed up the different scenarios where these errors occur, so if this issue re-occurs, please re-open and I'll investigate it more.

(related #84)
