### ISSUE TITLE
[Feature Request] Sort by recently added in songs library

### ISSUE THREAD

**Issue by FurkanToprak** [zachomedia/apple-music-webplayer#91]
Will there be a feature to sort playlists by recently added/artist/etc. for the songs library? While this seems trivial, it's the only feature the website lacks to make it a substantial substitute for apple music. Also, the alphabetic sorting mechanism in the songs playlist is very inconvenient for huge libraries and locating recently added songs that the user is not accustomed to. For example, I sometimes don't remember the names of new songs I add.

Thanks,

Furkan

PS: I really appreciate you keeping up with the maintenance and development of the webplayer.

**Comment by zachomedia** [comment]
Thanks for the request @FurkanToprak.

I'm currently using the default sorting that comes out of the Apple Music APIs. I can implement sorting based on some of the fields in a song, but it's unlikely that I'll be able to sort by "recently added" since that information is not provided in the API. The only place that type of information is available is in the "Recent" tab.

**Comment by FurkanToprak** [comment]
@zachomedia Even that would be great. I just looked at other Apple Webplayers (i.e. musi.sh) and it indeed seems to be unavailable from the API. Sorting by field would go a long way and wouldn't be too difficult to implement.

**Comment by zachomedia** [comment]
@FurkanToprak I was hoping to have this done a while back but unfortunately didn't have much time to work on it over the past couple of months.

I've finally got an initial version of this that supports sorting by name, artist, album and length. I'll continue to improve this feature over time.
